### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cyantau** [thriving123/fuckTodayStudy#15]
### 最新版本下：长江大学登录异常
只修改`config.yml`与`system.yml`文件后（确信无误）

直接`python index.py`后
**错误栈详情**：
> Traceback (most recent call last):
  File "fuckTodayStudy\index.py", line 29, in main
    msg = working(user)
  File "fuckTodayStudy\index.py", line 47, in working
    today.login()
  File "fuckTodayStudy\todayLoginService.py", line 93, in login
    self.checkLogin()
  File "fuckTodayStudy\todayLoginService.py", line 87, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "fuckTodayStudy\login\casLogin.py", line 40, in login
    **soup = BeautifulSoup(str(form[1]), 'lxml')**
IndexError: list index out of range
14:55:46 list index out of range
14:55:46 正在发送邮件通知
Traceback (most recent call last):
...........

**经过测试：**
1. 将form[1]改成form[0]后，无此异常
2. data = self.session.post(self.login_url, params=params, allow_redirects=False)   返回码为401 登录失败

应该如何解决呢？

**Comment by cyantau** [comment]
**阅读了源码以及抓包后解答：**
- 一开始以为全是使用json格式交互的，后来发现不是。

- 登录流程使用的是**网页模拟登录**，需要操作dom树，而不同学校的登录地址在某些地方code不一样。

- 不过上面的问题中，id选择器返回的确实只有**0或1**个元素，使用`form[1]`有误
